### ISSUE TITLE
Launcher sometimes hangs on validating (busy)

### ISSUE THREAD

**Issue by stheno** [Alderon-Games/alderongames-launcher-bugs#2]
Once in a while, quite often actually the launcher hangs on 0/0 validating files on startup. Rendering the game unable to launch. Took 3 tries to relauncher the launcher, then afk for 5 mins before it correctly validated files again.

***PoT account: Stheno
ID: 283-992-485
Discord: Stheno5755***

**Comment by Tyrannorex91** [comment]
I have the same, the loading is very long and the validation is currently still pending.

**Comment by Poncho-PoT** [comment]
I recommend following these steps for now to avoid this process. https://gyazo.com/2e8f4a6fc10d9a052286b108b08901e4

**Comment by squeaks112** [comment]
@stheno are you still having this issue in the current launcher version? (v.1.1.10)

**Comment by stheno** [comment]
I tried to duplicate this on the new patch and could not. Seems resolved.

**Comment by Tyrannorex91** [comment]
Sorry for my long answer but I'll try this, thanks. :)
