### ISSUE TITLE
AI labled wrong name

### ISSUE THREAD

**Issue by vividsky352** [Alderon-Games/alderongames-launcher-bugs#24]
![image](https://user-images.githubusercontent.com/53712729/66850409-ae3b2c80-ef70-11e9-9dd3-ecb08e1eac56.png)
kentrosaurus in the AI demo is labeled stegosaurus

**Comment by vividsky352** [comment]
![image](https://user-images.githubusercontent.com/53712729/66850491-d460cc80-ef70-11e9-9c0a-56c2be6c3e14.png)

**Comment by vividsky352** [comment]
I'd also like to add that I have not seen any stegosaurs 3 kentro have spawned in, may need testing to see if kentro over writt stego

**Comment by Doritodust** [comment]
This is the incorrect github to be posting bugs from the game. Only bugs relating to the launcher are to be posted here. This bug has also been posted on the PoT demo github.
