### ISSUE TITLE
File Verification Failure

### ISSUE THREAD

**Issue by broke4089** [Alderon-Games/alderongames-launcher-bugs#25]
**Expected Behavior:** Normal startup
-----------------------------------
**Current Behavior:** Issue regarding the verification of the game/local files.
----------------------------------
**Launcher Version:** 1.1.16
**Demo Version:** 0.0.0.3322 (Out of date, due to file verification error)
**Alderon Games Account:** 896-803-604
-----------------------------------
**Replication:** I don't know if you can replicate this; I was just updating the launcher while tabbed out doing other things. I was in a Discord V.C., Minecraft Bedrock (accidentally opened), and Chrome.
--------------------------------------
**Evidence:** 
![image](https://user-images.githubusercontent.com/54255702/66878572-750eb680-ef88-11e9-8100-97c0c0c866ba.png)
-----------------------------------------
**PC Build:** 
RAM: 16.0 GB
System Type: 64-bit OS (Windows 10)
Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 GHz

**Comment by broke4089** [comment]
Second time around: All the files have been verified successfully, the demo seems to have updated.

**Comment by Doritodust** [comment]
Issue seems to have sorted itself out based of users report, so the issue will be closed.
