### ISSUE TITLE
Launcher Loading Verifying Files again

### ISSUE THREAD

**Issue by Karasura** [Alderon-Games/alderongames-launcher-bugs#3]
Whenever I open the launcher and start switching between the two games, PoT keeps loading, again and again, the Verifying Files. I do not close the launcher in this time
https://youtu.be/WUXLpJqL2gg
(Later with more files to load this could be maybe annoying)

**Comment by Poncho-PoT** [comment]
https://gyazo.com/aae1cfc27f4deba3ff4076566f45f176 Another instance. I recommend following these steps for now to avoid this process. https://gyazo.com/2e8f4a6fc10d9a052286b108b08901e4

**Comment by Doritodust** [comment]
When switching between Breaking point and Path of Titans, the PoT files do not validate every time like what was shown in the video link. Is this still happening to you?
Launcher Version: 1.1.14

**Comment by Doritodust** [comment]
This issue will be closed due to lack of evidence for the current launcher version: 1.1.15 

If this issue occurs again please post here and this issue will be reopened.
