### ISSUE TITLE
Infinite login

### ISSUE THREAD

**Issue by sstarki** [Alderon-Games/alderongames-launcher-bugs#30]
The second day I can not enter the game. When I start through the launcher, they ask me to enter my account, after entering the data nothing happens. I reinstalled the game and logged in launcher, but nothing helped
![dsdsd](https://user-images.githubusercontent.com/57593079/68545510-57563500-0400-11ea-874f-80759e914f9d.png)

**Comment by deathlyrage** [comment]
This issue has now been fixed in the latest launcher version please give it a shot!.
