### ISSUE TITLE
Launcher Bug - OS not current?

### ISSUE THREAD

**Issue by Avallore** [Alderon-Games/alderongames-launcher-bugs#32]
I get this each time I boot up the game, someone else in the discord also had one for MAC as well... 

Far as I know there are no updates for me to get to this version of windows 10, so I'm kinda scratching my head.

![image](https://user-images.githubusercontent.com/58483829/70076111-1b139000-15cc-11ea-8f62-359866745731.png)

**Comment by deathlyrage** [comment]
Going to close this as we have a troubleshooting article to solve this problem: https://alderongames.com/windows-outdated
