### ISSUE TITLE
Download size of the whole demo every update

### ISSUE THREAD

**Issue by puphyin** [Alderon-Games/alderongames-launcher-bugs#33]
- Every update it doesnt seem to actually validate all existing files resulting in a larger download and longer time 

**Build Information**

- Game Version: 0.0.0.4262 Shipping
- Operating System: Windows 10
![image](https://user-images.githubusercontent.com/55628082/70383072-814b3a80-195f-11ea-974b-d7231f39c872.png)

![image](https://user-images.githubusercontent.com/55628082/70383076-8a3c0c00-195f-11ea-9d2b-665ddc55d813.png)

**Comment by jerryperez1969** [comment]
It appears that this problem has been addressed in this mornings patch update 0.0.0.4869, it no longer downloads the entire files but rather the files that "need" updating.
