### ISSUE TITLE
Launcher Requiring 2 Boot Ups (Crashes On First Opening, MAC)

### ISSUE THREAD

**Issue by Spyrofan00** [Alderon-Games/alderongames-launcher-bugs#34]
**Expected Behavior**

Launcher loads after running/opening.

**Current Behavior**

Launcher crashes/closes itself on the first attempt, but on the second attempt loads perfectly fine.

**Reproduction Steps**

    Simply open/run the Alderon Games Launcher

**Evidence (Screenshots & Videos)**

None available. Since the launcher simply closes itself.

**Crash Logs**

None, as it closes before it can even load anything.
Build Information

**Launcher.**

Launcher Version: 1.1.18 (This is a launcher issue that has existed before this update, this is not the Demo itself, but game version at time of posting is 0.0.0.4215)

Operating System & Version: Mac OS Mojave (10.14.6)

Alderon Games ID: 451-319-402

_Copy pasted from other thread due to accidental misposting_

**Comment by deathlyrage** [comment]
Closing this issue as its most likely fixed quite some time ago, if it still happends let us know and we will reopen it.
