### ISSUE TITLE
Using Direct option causes Static Splash Screen 

### ISSUE THREAD

**Issue by jerryperez1969** [Alderon-Games/alderongames-launcher-bugs#35]
when i go to:
Play Game\Multi Player Exploration\entered server name\entered IP address \clicked "DIRECT"
and it went into the POT splash screen with Trike running in lower right corner, but i couldn't escape or quit.

had to run task manager and end the process to get out  i understand that DIRECT feature may not be available yet so maybe that's why it wasn't connecting but at any rate there should be a "Cancel" option or Quit option to avoid pressing the Ctrl Alt Delete to reach task man

**Comment by deathlyrage** [comment]
Sorry for the late response but this should be posted on the other bugtracker if this is still happening. Which is the in-game one.

https://alderon.games/demobug
