### ISSUE TITLE
Stuck In A constant Login Loop

### ISSUE THREAD

**Issue by Duccky** [Alderon-Games/alderongames-launcher-bugs#36]
Every time I go to login to the Launcher I get a flash of "Checking for Updates" then it goes right back to asking me for my login information, I would greatly appreciate some help here because I greatly enjoy this game.  
      #30 [Capture](https://user-images.githubusercontent.com/59746648/72182767-6a0dcb80-33a9-11ea-91e6-3a661192ca97.PNG)

**Comment by deathlyrage** [comment]
This issue has now been fixed in the latest launcher version please give it a shot!.
