### ISSUE TITLE
Unable to Launch Launcher

### ISSUE THREAD

**Issue by Deafo1** [Alderon-Games/alderongames-launcher-bugs#37]
Hello,

I've done several different methods to attempt to launch the Alderon Launcher, such as reinstalling it, putting the launcher in the Applications folder, and several calculations to break through the Privacy and Security System. And I still get the same result which is the image below.

I'm more than happy to explain more if you have more questions for me.

<img width="432" alt="Screen Shot 2020-01-12 at 2 49 28 PM" src="https://user-images.githubusercontent.com/59807636/72226156-2783f480-354b-11ea-9ca9-f51c42362740.png">

**Comment by deathlyrage** [comment]
This issue has now been fixed in the latest launcher version please give it a shot!.
