### ISSUE TITLE
Stuck on 4-8MB left of download.

### ISSUE THREAD

**Issue by theonlyRaw** [Alderon-Games/alderongames-launcher-bugs#4]
![Screenshot_312](https://user-images.githubusercontent.com/54249603/63230405-c6413a80-c1d1-11e9-8c74-b621d6cea2c7.png)
The first time I launched the AG launcher, I click "install" for PoT. I even download in the default file path if gives me. It will then validate any existing files, and then download the rest. But each time it takes literally hours and hours, sometimes days, to get it to download to 4 MB or 8MB left. 

It will stay at this amount left, even if I refresh the launcher. When I do refresh the launcher and go to install PoT again to validate where I left off, it sometimes gives me "Network Error" or "Session timed out." After about 10 attempts, it then proceeds to validate. It will then download up until 4MB or 8MB again. It doesn't get any further than that. I've made an exception in my firewall, just in case. I refresh the launcher after doing so, and still no change.

**Comment by TricksyKenbbit** [comment]
I get a very similar issue.
I get stuck at 8MB, and the right side of the bar says 6P, then occasionally switches to 4P for a while, then back to 6P. Other than that, it just sits there, but it says something other than 'Downloading @ 0.00 B/s'.
![launcherBugPoT](https://user-images.githubusercontent.com/54282930/63283223-89268800-c265-11e9-879a-4c0682dc8ca3.PNG)
I also noticed that when I restart the launcher it has the button to install, and then a 'find installation directory' if it's already been installed. I can find the folder through Windows Explorer (and by clicking the button to bring you to the folder from the launcher) but when I tell it to find my game through looking for the install folder, I get an error.
![launcherBug2PoT](https://user-images.githubusercontent.com/54282930/63283222-89268800-c265-11e9-842f-332d5af17730.PNG)
I've tried restarting the launcher, logging out and in, and restarting my computer. No change to either issue.

**Comment by theonlyRaw** [comment]
Update: redownloading on v1.1.9

**Comment by squeaks112** [comment]
@theonlyRaw @TricksyKenbbit is this still happening on the current updated launcher version? (v1.1.10)

**Comment by TricksyKenbbit** [comment]
@squeaks112 It is for me, yes. I even 'uninstalled' (deleted the demo folder, because there's no proper uninstall if it's not recognized as a program) and reinstalled, and it's still happening.

**Comment by theonlyRaw** [comment]
@squeaks112 Yes I just updated to 1.1.13 and having the same issue.

**Comment by theonlyRaw** [comment]
1.1.14 is giving the same issue but is stuck at 24MB left of download.
![Screenshot_336](https://user-images.githubusercontent.com/54249603/64012574-97856700-cae3-11e9-8232-c8494d0d7303.png)

**Comment by theonlyRaw** [comment]
@Doritodust I updated to 1.1.15 and the download went through! It took all night but I'm able to launch the demo now.

**Comment by Doritodust** [comment]
Thank you for the response. It seems this bug was fixed in one of recent launcher updates. If anyone experiences this issue again please post here and this ticket will be reopened.
