### ISSUE TITLE
Unreal Engine 4 Crash Reporter. Can't launch the game

### ISSUE THREAD

**Issue by Dallah45** [Alderon-Games/alderongames-launcher-bugs#43]
## Expected Behavior
Game launches after installing and clicking "Play" button
## Current Behavior
The next day, even after reboot, everything is the same. I open the game through the launcher and see a window with the UE Crash report
## Reproduction Steps
-Open the game through Alderon Games launcher
-See a small window with the name of the game
-See a window with the Unreal Engine 4 Crash Reporter

## Evidence (Screenshots & Videos)
![image](https://user-images.githubusercontent.com/62597348/77418776-0bfd5b80-6dd0-11ea-876e-94d87cf9c168.png)

**Crash logs**:
LoginId:5790168b4757585005054281c9dd4ab5
EpicAccountId:

Fatal error: [File:Unknown] [Line: 258] D3DRHI->GetFactory()->CreateSwapChain(DXGIDevice, &SwapChainDesc, SwapChain.GetInitReference()) failed at C:/Jenkins/workspace/ue4-424/Engine/Source/Runtime/Windows/D3D11RHI/Private/Windows/WindowsD3D11Viewport.cpp:210 with error E_INVALIDARG

PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
PathOfTitans_Win64_Shipping
kernel32
ntdll
Zip file with crash logs: https://yadi.sk/d/2rvqW7_V4jih9A

## Build Information

**Game Version:** 0.0.0.5590

**Operating System & Version:**
Windows 10 Pro & 1909

**Alderon Games ID:** 004-762-408

**Comment by deathlyrage** [comment]
This needs to be on the game bugtracker not the launcher one.
