### ISSUE TITLE
Auto-Login Prevents you from Logging into a different account (stuck in loop)

### ISSUE THREAD

**Issue by Paleocolour** [Alderon-Games/alderongames-launcher-bugs#44]
Launcher version: v1.1.29

Issue:
Auto-Login Prevents you from Logging into a different account, becomes stuck in an auto-login loop.

Reproduction steps:
- Enable auto-login and log in to launcher
- after it loads, click the logout button
- let the login screen open and notice it keeps your credentials saved and automatically logs you back into the launcher.
- unable to log into new account, stuck in loop

Video: https://cdn.discordapp.com/attachments/193204194117681154/696479133714088016/wDYNPXQX5p.mp4

OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363

**Comment by Paleocolour** [comment]
NOTE: A workaround for this bug is to quickly close the login screen between step 2-3 so it won't relog you back in. Reopening the launcher after closing it will not auto-log you back in.

**Comment by AlderonDingo** [comment]
Issue is still occurring in launcher build 1.1.70 

Community footage: 

https://user-images.githubusercontent.com/102556211/168126636-bf68eaa1-7e79-4be2-85c6-0a44c1c1162d.mp4
