### ISSUE TITLE
Game start error (Unreal arguments)

### ISSUE THREAD

**Issue by Auhrus** [Alderon-Games/alderongames-launcher-bugs#48]
## Expected Behavior
The game should start

## Current Behavior
The game does not start :)

**Additional info:**
If I start the game via the "PathOfTitans-Win64-Shipping.exe" and log in there everything works (a small workaround).

## Reproduction Steps
- I enter the Lancher
- Press "Play" on the bottom right
- Then there is short Preparing and I am asked for administrator authorization
-This is confirmed with yes and the error appears in Launcher

## Evidence (Screenshots & Videos)
![grafik](https://user-images.githubusercontent.com/57270834/82840498-1c66ab00-9ed3-11ea-8fb8-a1339a584e14.png)

## Build Information

**Game Version:** 0.0.0.7528

**Operating System & Version:**
![grafik](https://user-images.githubusercontent.com/57270834/97110693-ed9b6d80-16da-11eb-9a2c-d1d4b7bdaff2.png)

**Alderon Games ID:** 806-213-446

**Comment by UncleToppy** [comment]
I'm currently having this error too. Any update on a fix?
