### ISSUE TITLE
Re-Update when switching between games

### ISSUE THREAD

**Issue by Steeltone** [Alderon-Games/alderongames-launcher-bugs#5]
If I click on Breaking Point, then back to Path of Titans, it forces the game to update each time I switch between the two.
Here if a GIF showing the launcher is up to date and it being forced to reupdate.

https://gyazo.com/6214270937b5781144912fa3b4e1fc50

**Comment by squeaks112** [comment]
@Steeltone does it actually re-update or just re-verify? also please see https://github.com/deathlyrage/alderongames-launcher-bugs/issues/3

**Comment by Steeltone** [comment]
Since the launcher updated I have been unable to replicate it.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
