### ISSUE TITLE
Claims Windows is Out of Date

### ISSUE THREAD

**Issue by buttonsmashley** [Alderon-Games/alderongames-launcher-bugs#51]
Every time I start the launcher and when I launch the game it pops up with an error saying that my version of Windows is out of date and needs to be updated or else it will not work with the client or associated games. I say okay and then the client and game seems to work just fine after that. Windows should be up to date, I checked for updates and it says I'm all good so I figure it must just be a mix up somewhere.

**Comment by deathlyrage** [comment]
https://alderon.games/windows-outdated
