### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by HMS-Lion** [Alderon-Games/alderongames-launcher-bugs#53]
Whenever I attempt to log in whenever I use my password, steam or discord log in the launcher simply closes and asks me to log in again in a never ending loop.

![image](https://user-images.githubusercontent.com/68515832/87883772-92821c80-ca01-11ea-9d31-575e85be07fc.png)

![image](https://user-images.githubusercontent.com/68515832/87883778-a3329280-ca01-11ea-820c-1c1fca1c227b.png)

![image](https://user-images.githubusercontent.com/68515832/87883857-39ff4f00-ca02-11ea-9e67-c97cc6d36421.png)

**Comment by Sanjikunsgirl** [comment]
Hello, I am currently facing the same problem. I have disabled my firewall, added the launcher to my allowed list, updated to the newest version of windows/ my drivers. I have already uploaded my logs to the site as per a very helpful team member has suggested. I am just currently adding my name to this current problem. I also have a dropbox of a recording I did, but it as the same as HMS--Lion has stated, it is just a current unending loop of wanting to log in. All the attempts seem to have made no progress in improving it and at this point I simply will add what information I can to help a solution be developed as quickly as possible. Thank you again for all the hard work you all are doing.[https://www.dropbox.com/s/8qt3o0ydyp46ss6/20201111_152724.mp4?dl=0](url)

**Comment by deathlyrage** [comment]
@Sanjikunsgirl did you try with the latest launcher patch?

**Comment by Sanjikunsgirl** [comment]
@deathlyrage How do I get the latest launcher patch? Do I simply uninstall and reinstall it? Because if it's 1.1.48 that is the one I have currently.

**Comment by deathlyrage** [comment]
Okay thanks for letting us know, 1.1.48 is the latest version. We will investigate and fix this issue @Sanjikunsgirl

**Comment by Sanjikunsgirl** [comment]
Update: I installed the latest patch (1.1.51) and it is still putting me through the log in loop. At first I thought progress had been made because it showed me a download bar, but nothing came from it.

**Comment by Sanjikunsgirl** [comment]
Update: Installed the latest patch ( 1.1.54) still putting me through the loop.

**Comment by deathlyrage** [comment]
> Update: Installed the latest patch ( 1.1.54) still putting me through the loop.

I have a workaround that might help, can you try making a new windows user account and installing on there?

**Comment by Sanjikunsgirl** [comment]
@deathlyrage Sorry it took so long for me to get back to you but that worked?! It's downloading the game now, thank you so much!

**Comment by deathlyrage** [comment]
This issue has now been fixed in the latest launcher version and should now correctly work for your other user account.
