### ISSUE TITLE
Server List Stays Open Behind Main Menu

### ISSUE THREAD

**Issue by Taigatrees** [Alderon-Games/alderongames-launcher-bugs#56]
## Expected Behavior
Server list should remain open or close completely to the game's main menu if the server you are attempting to join is full.

## Current Behavior
Tried to join a server that was full and then the server list remained behind the main menu, not able to be interacted with. Have to quit the game to get it to clear or just select Multiplayer to return to the server list.
## Reproduction Steps
-Start up the game from the launcher
-Select Multiplayer
-Select Full server
-Receive error message about the server being full
-Kicked back to main menu with the server list inactive behind it

## Evidence

https://imgur.com/a/d5bwziC

## Build Information

**Game Version:** 0.0.0.8493

**Windows 10 - Taigatrees**

**Comment by OscarMeFer** [comment]
Yes, i have the same problem

+1! 👍🙌
