### ISSUE TITLE
Login to launcher

### ISSUE THREAD

**Issue by Foul-Buccaeer** [Alderon-Games/alderongames-launcher-bugs#6]
Hello, any time I try to open the launcher it always flashes a validation error and requires me to log in sometimes twice before being able to have access to Path of Titans. Unsure if this is intended or a bug.

**Comment by squeaks112** [comment]
@Foul-Buccaeer could you possibly get a video for us? c:

**Comment by Foul-Buccaeer** [comment]
Short answer: no. Is there something else I can provide?

**Comment by squeaks112** [comment]
@Foul-Buccaeer could you provide a screenshot at all of the validation error maybe? any extra info is useful :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
