### ISSUE TITLE
Unable to roar or run

### ISSUE THREAD

**Issue by ghost** [Alderon-Games/alderongames-launcher-bugs#60]
Unable to roar or run
![AA479272-EBA0-43BE-A314-957C46946EDF](https://user-images.githubusercontent.com/71244490/97658618-00d77180-1a2a-11eb-9afa-3a6d0e072c5b.png)
Picture above is me trying to roar or run
Alderon Games ID: 624-873-649 
Device: IPhone XR version 14.1
Game versión: 0.0.0.9894

**Comment by garryt777** [comment]
Mine does the same thing as sucho. It won’t run or roar. He’s gotta run and roar. I’m on iOS 14.1 as well, and iPhone 7.
