### ISSUE TITLE
Controller Support Not working/Registering

### ISSUE THREAD

**Issue by Misume** [Alderon-Games/alderongames-launcher-bugs#61]
Usually I use controller on the windows version, as I can't WASD, it hurts too much.

After yesterday's update, the controller I've been using has stopped working. I've tried several ways to fix this issue manually, but nothing works, and I know it's worked fine before as my husband uses it too and now he's having the same issue as me.
I use the program DS4 Windows to make it act like an xbox controller, if I need to give any more information please let me know!

Game Version: 0.0.0.9894

Operating System: Windows 10
 Alderon Games ID: 703-866-906

**Comment by deathlyrage** [comment]
this is the launcher bugtracker not the game one.
