### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by suchodude** [Alderon-Games/alderongames-launcher-bugs#62]
![B9314CEB-5600-4270-BAC3-17F1AF2CAA04](https://user-images.githubusercontent.com/73714948/97740568-d8965400-1ab7-11eb-85ee-24cfaa7e2cb5.png)
whenever A swimming dino comes near great lake it bugs out the screen goes black
I attempted to send a pic,but to me it seems like text vomit so im not sure how it will send but the text should be a photo,if not that’s what it was

**Comment by deathlyrage** [comment]
this is the launcher bugtracker not the game one.
