### ISSUE TITLE
Glitchy gameplay or screen

### ISSUE THREAD

**Issue by garryt777** [Alderon-Games/alderongames-launcher-bugs#63]
Expected behavior: not glitch, or freeze, or go black to where I can’t do anything. Should be able to swim.
Current behavior: gets to a point in one spot where I literally can’t do anything at all, nothing. Game freezes, and goes glitchy, and black in Great Lake near talons point. Can’t even log out.
Reproduction steps: please help get to where I can swim without glitching, or whatever it’s doing. That’s all I know. It’s just swimming dinos in the one spot. 
Evidence:pic was soupy to be video but can’t put that here
![ED777F61-9D5A-4FC0-8804-BE929B62A651](https://user-images.githubusercontent.com/73700978/97752185-e94fc580-1ac9-11eb-8fdd-bb2d15a8ecd3.png)
Build: iPhone 7 reg iOS 14.1
Game version: 0.0.0.9894
Alderon I.D: 449-382-483

**Comment by garryt777** [comment]
I hope I did this correctly I’m sorry if I didn’t idk how to put video either sorry

**Comment by ghost** [comment]
Does it still freeze or crashes on iOS??

**Comment by garryt777** [comment]
Yes, definitely, that’s actually the bug I mean along with this title I have already. Yep it still freezes and crashes on iOS DEFINITELY! Now in five different spots, one on land, with two different dinos now. I’m not wanting to go to Great Lake now, lol. So same problem more spots: one on land near Great Lake, and two brothers hallow at the corpse, the one near talons, one in between both those in water, one in water at the pond at little brook meadow attached to Great Lake, and one in water of Great Lake by plateau hill haven also. Just wanted to let you all know the different spots now. It happens to spino and sucho so far. Thank u all.

**Comment by deathlyrage** [comment]
this is the launcher bugtracker not the game one.
