### ISSUE TITLE
Games still freezing. Even after update said it fixed it :(

### ISSUE THREAD

**Issue by ghost** [Alderon-Games/alderongames-launcher-bugs#64]
It keeps freezing every 30 min. Even this update 0.0.0.9894 said it fixed it 
![image](https://user-images.githubusercontent.com/71244490/97768146-4786a380-1ade-11eb-83eb-ed88ba9a5357.png)

Alderon Games ID: 624-873-649
Device: IPhone XR version 14.1
Game versión: 0.0.0.9894

**Comment by deathlyrage** [comment]
this is the launcher bugtracker not the game one.
