### ISSUE TITLE
Lambeosaurus legs dance glitch

### ISSUE THREAD

**Issue by garryt777** [Alderon-Games/alderongames-launcher-bugs#66]
Expected behavior: for legs to be still while idle, and move normally while walking.

Current behavior: when the Lambeo is standing idle; and at times while walking, the legs do a weird dance in circles.

Reproduction steps: please, when you can fix legs so they don't move in said circles. To walk, and stand, or sit normal without the glitch shaking them. Have them straight, not broken looking. Thank you for your time, and help. I appreciate you all!

Evidence: photos here:
![110D285D-D48A-438F-9F2C-E919DC14BD99](https://user-images.githubusercontent.com/73700978/98810659-89bcb880-23ed-11eb-8d3b-aad45cb8715e.png)

![16DED33E-43BC-4856-883D-340F2D757FDF](https://user-images.githubusercontent.com/73700978/98810705-9c36f200-23ed-11eb-8d53-7a04ccfd6b12.png)

Game version: 0.0.0.10071

Alderon I.D: 449-382-483

**Comment by deathlyrage** [comment]
this is the launcher bugtracker not the game one.
