### ISSUE TITLE
AG logo on launcher opens launcher website

### ISSUE THREAD

**Issue by Nardalis** [Alderon-Games/alderongames-launcher-bugs#7]
Pressing the AG logo on the launcher opens up a page to the launcher download. This seems odd...

**Comment by Doritodust** [comment]
When clicking on the AG logo I am brought to the Alderon Games website: https://alderongames.com/
Are you still brought to the launcher download when clicking on the AG logo?
Launcher Version: 1.1.14

**Comment by Nardalis** [comment]
Correct, it seems to be fixed. Version 1.1.14 too, not yet updated.
