### ISSUE TITLE
Launcher Login Failing

### ISSUE THREAD

**Issue by Rbengy** [Alderon-Games/alderongames-launcher-bugs#71]
I have the most recent launcher, and was sent a code for the early access game. I have an account made, and it says the code is valid and activated.
The problem is that whenever I load the launcher, it doesn't sign me in. I login with my usual account, but it starts, exits, and then goes back to the login page. It could be my pc, as it worked for a friend of mine, but it didn't work for me.
Any advice on how to fix this? I've been trying to login to the launcher since July.

**Comment by deathlyrage** [comment]
This issue has now been fixed in the latest launcher version please give it a shot!.
