### ISSUE TITLE
Map bug at water fall cave around pleasant hill haven 

### ISSUE THREAD

**Issue by garryt777** [Alderon-Games/alderongames-launcher-bugs#72]
Expected behavior: To be able to get out of little pond under the waterfall inside the cave at pleasant hill haven.

Current behavior: If you jump in, or fall in the pond you can't get out. Then as I kept trying to I died. 

Reproduction steps: Please fix a way to climb back up as any dinosaur, without loosing stamina, or life. 

Evidence: I have a video, but I can't post it here, and it has happened to others as well.

**Comment by deathlyrage** [comment]
wrong bugtracker, this is for the launcher.
